leftnav:
- identifier: 601c56ad-d3d1-4713-8fa0-fec112adfacb
  name: Boys
  pageRef: /pages/tutankhamen
  weight: 10
- identifier: e93820a3-66a6-4928-b9a7-96c434a4ec6a
  name: Pyramids Inscriptions Mathematics
  pageRef: /pages/pyramids-inscriptions-mathematics
  weight: 20
