leftnav:
- identifier: 601c56ad-d3d1-4713-8fa0-fec112adfacb
  name: Boys
  pageRef: /pages/tutankhamen
  weight: 10
- identifier: e93820a3-66a6-4928-b9a7-96c434a4ec6a
  name: Pyramids
  pageRef: /pages/pyramids
  weight: 20
- identifier: f53b32fd-46fd-489c-8fde-8f1e3b509d88
  name: Not exist
  pageRef: /pages/nowhere
  weight: 30
